name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build AMD64 binary
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -o nanoHttp-linux-amd64 cmd/nanohttp/main.go
          chmod +x nanoHttp-linux-amd64

      - name: Build ARM64 binary
        env:
          GOOS: linux
          GOARCH: arm64
        run: |
          go build -o nanoHttp-linux-arm64 cmd/nanohttp/main.go
          chmod +x nanoHttp-linux-arm64

      - name: Build macOS AMD64 binary
        env:
          GOOS: darwin
          GOARCH: amd64
        run: |
          go build -o nanoHttp-darwin-amd64 cmd/nanohttp/main.go
          chmod +x nanoHttp-darwin-amd64

      - name: Build macOS ARM64 binary
        env:
          GOOS: darwin
          GOARCH: arm64
        run: |
          go build -o nanoHttp-darwin-arm64 cmd/nanohttp/main.go
          chmod +x nanoHttp-darwin-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nanoHttp-linux-amd64
            nanoHttp-linux-arm64
            nanoHttp-darwin-amd64
            nanoHttp-darwin-arm64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 